apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: task-management-hub-frontend
  annotations:
    github.com/project-slug: ank10t/task-management-hub
  description: React frontend application
  tags:
    - react
    - frontend

spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: task-management-hub-platform