apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: staffing-app
  description: Staffing management platform
  tags:
    - react
    - nodejs

spec:
  type: service
  lifecycle: experimental
  owner: guests