apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: task-management-hub-backend
  description: Node.js backend API
  tags:
    - nodejs
    - backend

spec:
  type: service
  lifecycle: experimental
  owner: engineering-team
  system: task-management-hub-platform
  providesApis:
    - task-management-api